# Generated by Django 4.2.7 on 2024-02-15 16:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='additional_field',
            field=models.CharField(default=datetime.datetime(2024, 2, 15, 16, 36, 42, 333511, tzinfo=datetime.timezone.utc), max_length=50),
            preserve_default=False,
        ),
    ]
