# Generated by Django 4.2.7 on 2024-02-18 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='additional_field',
        ),
    ]
