# Generated by Django 4.2.7 on 2024-02-18 08:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_remove_userprofile_additional_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='additional_field',
            field=models.CharField(default=datetime.datetime(2024, 2, 18, 8, 6, 30, 727602, tzinfo=datetime.timezone.utc), max_length=50),
            preserve_default=False,
        ),
    ]
