# Generated by Django 4.2.7 on 2024-02-18 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
