# Generated by Django 4.2.7 on 2024-02-24 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_rename_user_userprofile_users_alter_user_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='users',
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
