# Generated by Django 4.2.7 on 2024-03-27 09:21

from django.db import migrations, models
import shop.models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_remove_userprofile_users_delete_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profileimage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=150, null=True)),
                ('proimg', models.ImageField(blank=True, null=True, upload_to=shop.models.getFileName)),
            ],
        ),
    ]
