# Generated by Django 4.2.7 on 2024-03-27 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_profileimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='profileimage',
            name='userid',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
