# Generated by Django 4.2.7 on 2024-03-27 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0015_profileimage_userid'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profileimage',
        ),
    ]
